In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('/content/drive/MyDrive/airbnb/listings.csv')

In [4]:
pd.set_option('display.max_rows',None)

pd.set_option('display.max_columns',None)

In [5]:
df.sample(3)

,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,listing_years,days_since_last_review,amenities_count,amenity_kitchen,amenity_microwave,amenity_refrigerator,amenity_ac,amenity_pets,amenity_parking,amenity_wifi,has_email_verified,has_phone_verified,has_work_email,host_response_rate_missing,host_acceptance_rate_missing,log_revenue
1273,within an hour,100.0,97.0,1,1.0,1.0,1,1,28803.0,35.56555,-82.51827,guest suite,Entire home/apt,2.0,1.0,1.0,1.0,64.0,1.0,15.0,1.0,2.0,15.0,15.0,1.3,15.0,1,11.0,41.0,71.0,251.0,54.0,15.0,3.0,82.0,24.0,90.0,5760.0,4.93,4.93,4.81,4.91,4.98,4.96,4.89,0,1.0,1.0,0.0,0.0,2.14,10,15.0,50,1,1,1,1,0,1,1,1,1,0,0,0,8.658866
69,within a few hours,80.0,65.0,1,3.0,4.0,1,1,28806.0,35.58445,-82.58051,guest suite,Entire home/apt,4.0,1.0,1.0,1.0,84.0,2.0,1125.0,1.0,2.0,1125.0,1125.0,1.3,1125.0,1,11.0,38.0,68.0,343.0,256.0,4.0,0.0,79.0,12.0,24.0,2016.0,4.63,4.81,4.80,4.92,4.84,4.75,4.55,0,3.0,3.0,0.0,0.0,2.03,13,57.0,38,1,1,1,1,1,1,1,1,1,0,0,0,7.609367
72,within an hour,100.0,100.0,1,1.0,3.0,1,1,28806.0,35.57364,-82.57785,loft,Entire home/apt,2.0,1.0,1.0,1.0,77.0,1.0,60.0,1.0,2.0,1125.0,1125.0,1.1,1125.0,1,9.0,34.0,63.0,74.0,1062.0,29.0,2.0,74.0,50.0,174.0,13398.0,4.92,4.97,4.96,4.96,4.96,4.89,4.86,1,1.0,1.0,0.0,0.0,8.38,13,15.0,40,1,1,1,1,0,1,1,1,1,0,0,0,9.502935

In [6]:
# changing dtype to object
df['neighbourhood_cleansed']=df['neighbourhood_cleansed'].astype('object')

In [7]:
# selecting object columns
cat_cols=df.select_dtypes(include=['object']).columns

In [8]:
# selecting numeric columns
df.select_dtypes(include=['number']).columns

Index(['host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_listings_count', 'host_total_listings_count',
       'host_has_profile_pic', 'host_identity_verified', 'latitude',
       'longitude', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'has_availability', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'listing_years', 'days_since_last_review', 'amenities_count',
       'amenity_kitchen', 'amenity_microwave', 'amenity_refrigerator',
       'amenity_ac', 'amenity_pets', 'amenity_parking', 'amenity_wifi',
       'has_email_verified', 'has_phone_verified', 'has_work_email',
       'host_response_rate_missing', 'host_acceptance_rate_missing',
       'log_revenue'],
      dtype='object')

In [9]:
# keeping columns that are not encoded
num_columns=['host_response_rate', 'host_acceptance_rate',
       'host_listings_count', 'host_total_listings_count',
        'latitude',
       'longitude', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'has_availability', 'availability_30',
       'availability_60', 'availability_90', 'availability_365',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'listing_years', 'days_since_last_review', 'amenities_count']

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [11]:
# preprocessor
preprocessor=ColumnTransformer(
    transformers =[
        ('num',StandardScaler(),num_columns),
        ('cat',OneHotEncoder(drop='first',handle_unknown='ignore'),cat_cols)
    ],
    remainder='passthrough'
)

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

In [13]:
# Pipeline
pipeline=Pipeline(
    steps=[
        ('preprocessing',preprocessor),
        ('model',LinearRegression())
    ]
)

In [14]:
# train test split
from sklearn.model_selection import train_test_split
X=df.drop(columns=['estimated_revenue_l365d','log_revenue'])
y = df['log_revenue']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet

In [ ]:
# param grid for grid search cv
param_grid = [
    {
        'model':[LinearRegression()]
    },
    {
        'model':[Ridge()],
        'model__alpha': np.logspace(-3, 3, 20)
    },
    {
        'model':[Lasso(max_iter=10000)],
        'model__alpha': np.logspace(-3, 3, 20)
    },
    {
        'model': [ElasticNet(max_iter=10000)],
        'model__alpha': [0.01, 0.1, 1, 10],
        'model__l1_ratio': [0.1, 0.5, 0.9]
}

]

In [18]:
from sklearn.model_selection import GridSearchCV

In [ ]:
# grid serach cv k fold cross validation on training set
grid=GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
    scoring='neg_root_mean_squared_error',
    n_jobs=-1
)
grid.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['host_response_rate',
                                                                          'host_acceptance_rate',
                                                                          'host_listings_count',
                                                                          'host_total_listings_count',
                                                                          'latitude',
                                                                          'longitude',
                                                                          'accommodates',
                                                                          'bathrooms',
                                                                          'bedrooms',
                                                                          'beds',
                                                                          'price',
                                                                          'minimum_nights',
                                                                          'maximum_nights',
                                                                          'min...
       1.83298071e-02, 3.79269019e-02, 7.84759970e-02, 1.62377674e-01,
       3.35981829e-01, 6.95192796e-01, 1.43844989e+00, 2.97635144e+00,
       6.15848211e+00, 1.27427499e+01, 2.63665090e+01, 5.45559478e+01,
       1.12883789e+02, 2.33572147e+02, 4.83293024e+02, 1.00000000e+03])},
                         {'model': [ElasticNet(max_iter=10000)],
                          'model__alpha': [0.01, 0.1, 1, 10],
                          'model__l1_ratio': [0.1, 0.5, 0.9]}],
             scoring='neg_root_mean_squared_error')

In [ ]:
print("Best model:", grid.best_params_)
print("Best CV RMSE:", -grid.best_score_)

Best model: {'model': Lasso(max_iter=10000), 'model__alpha': np.float64(0.0379269019073225)}
Best CV RMSE: 1.584389822935456

In [ ]:
# predicting on X_test
from sklearn.metrics import mean_squared_error
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)
rmse_test = np.sqrt(mean_squared_error(y_test, y_pred))
print("Test RMSE:", rmse_test)

Test RMSE: 1.4636562000472548

In [ ]:
# getting coefficients that were zeroed due to lasso regression
best_model = grid.best_estimator_
coefs = best_model.named_steps['model'].coef_
np.sum(coefs == 0)

np.int64(64)

In [ ]:
coefs

array([ 0.00000000e+00,  1.29242606e-01,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.04623509e-01,  0.00000000e+00,  2.43157835e-01, -0.00000000e+00,
        0.00000000e+00, -1.87741132e-01, -0.00000000e+00,  1.05771914e-02,
        0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -1.70631780e-01, -3.96692675e-02,  7.49667972e-02,
        0.00000000e+00,  1.31320442e+00,  2.41873023e-01,  2.08083691e-01,
        1.03774228e-01,  0.00000000e+00,  4.76890212e-02,  4.92276243e-01,
        0.00000000e+00,  0.00000000e+00,  1.40182921e-01, -0.00000000e+00,
       -1.04006970e-03,  0.00000000e+00, -2.40544592e-02, -1.96050944e+00,
        3.08218527e-02, -1.00402951e-03, -0.00000000e+00,  0.00000000e+00,
        2.20797987e-03, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  2.25477425e-01, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00])

In [ ]:
all_features = best_model.named_steps['preprocessing'].get_feature_names_out()

In [ ]:
import pandas as pd

coef_df = pd.DataFrame({
    'Feature': all_features,
    'Coefficient': coefs
})

# Sort by absolute importance
coef_df['Abs_Coefficient'] = coef_df['Coefficient'].abs()

coef_df = coef_df.sort_values(by='Abs_Coefficient', ascending=False)

coef_df

,Feature,Coefficient,Abs_Coefficient
43,num__days_since_last_review,-1.960509,1.960509
29,num__estimated_occupancy_l365d,1.313204,1.313204
35,num__review_scores_location,0.492276,0.492276
10,num__price,0.243158,0.243158
30,num__review_scores_rating,0.241873,0.241873
70,remainder__host_is_superhost,0.225477,0.225477
31,num__review_scores_accuracy,0.208084,0.208084
13,num__minimum_minimum_nights,-0.187741,0.187741
25,num__number_of_reviews_ltm,-0.170632,0.170632
38,num__calculated_host_listings_count_entire_homes,0.140183,0.140183
1,num__host_acceptance_rate,0.129243,0.129243
8,num__bedrooms,0.104624,0.104624
32,num__review_scores_cleanliness,0.103774,0.103774
27,num__availability_eoy,0.074967,0.074967
34,num__review_scores_communication,0.047689,0.047689
26,num__number_of_reviews_l30d,-0.039669,0.039669
44,num__amenities_count,0.030822,0.030822
42,num__listing_years,-0.024054,0.024054
15,num__minimum_maximum_nights,0.010577,0.010577
48,cat__host_response_time_within an hour,0.002208,0.002208
40,num__calculated_host_listings_count_shared_rooms,-0.001040,0.001040
45,cat__host_response_time_missing,-0.001004,0.001004
21,num__availability_60,0.000000,0.000000
20,num__availability_30,0.000000,0.000000
19,num__has_availability,-0.000000,0.000000
18,num__maximum_nights_avg_ntm,0.000000,0.000000
17,num__minimum_nights_avg_ntm,-0.000000,0.000000
16,num__maximum_maximum_nights,0.000000,0.000000
14,num__maximum_minimum_nights,-0.000000,0.000000
12,num__maximum_nights,0.000000,0.000000
6,num__accommodates,0.000000,0.000000
11,num__minimum_nights,-0.000000,0.000000
7,num__bathrooms,0.000000,0.000000
9,num__beds,0.000000,0.000000
2,num__host_listings_count,0.000000,0.000000
3,num__host_total_listings_count,0.000000,0.000000
4,num__latitude,0.000000,0.000000
5,num__longitude,0.000000,0.000000
0,num__host_response_rate,0.000000,0.000000
37,num__calculated_host_listings_count,0.000000,0.000000
33,num__review_scores_checkin,0.000000,0.000000
36,num__review_scores_value,0.000000,0.000000
24,num__number_of_reviews,0.000000,0.000000
23,num__availability_365,0.000000,0.000000
22,num__availability_90,0.000000,0.000000
28,num__number_of_reviews_ly,0.000000,0.000000
39,num__calculated_host_listings_count_private_rooms,-0.000000,0.000000
46,cat__host_response_time_within a day,-0.000000,0.000000
47,cat__host_response_time_within a few hours,0.000000,0.000000
49,cat__neighbourhood_cleansed_28715.0,-0.000000,0.000000
50,cat__neighbourhood_cleansed_28732.0,0.000000,0.000000
51,cat__neighbourhood_cleansed_28801.0,0.000000,0.000000
52,cat__neighbourhood_cleansed_28803.0,0.000000,0.000000
41,num__reviews_per_month,0.000000,0.000000
53,cat__neighbourhood_cleansed_28804.0,-0.000000,0.000000
54,cat__neighbourhood_cleansed_28805.0,-0.000000,0.000000
56,cat__property_type_bungalow,0.000000,0.000000
55,cat__neighbourhood_cleansed_28806.0,-0.000000,0.000000
58,cat__property_type_condo,0.000000,0.000000
59,cat__property_type_cottage,-0.000000,0.000000
60,cat__property_type_guest suite,-0.000000,0.000000
57,cat__property_type_cabin,0.000000,0.000000
62,cat__property_type_home,0.000000,0.000000
63,cat__property_type_loft,0.000000,0.000000
64,cat__property_type_rental unit,-0.000000,0.000000
65,cat__property_type_room,0.000000,0.000000
66,cat__property_type_townhouse,-0.000000,0.000000
67,cat__room_type_Hotel room,0.000000,0.000000
68,cat__room_type_Private room,-0.000000,0.000000
61,cat__property_type_guesthouse,0.000000,0.000000
69,cat__room_type_Shared room,-0.000000,0.000000
71,remainder__host_has_profile_pic,-0.000000,0.000000
72,remainder__host_identity_verified,-0.000000,0.000000
73,remainder__instant_bookable,-0.000000,0.000000
74,remainder__amenity_kitchen,0.000000,0.000000
75,remainder__amenity_microwave,0.000000,0.000000
76,remainder__amenity_refrigerator,0.000000,0.000000
77,remainder__amenity_ac,0.000000,0.000000
78,remainder__amenity_pets,-0.000000,0.000000
79,remainder__amenity_parking,0.000000,0.000000
80,remainder__amenity_wifi,0.000000,0.000000
81,remainder__has_email_verified,-0.000000,0.000000
82,remainder__has_phone_verified,0.000000,0.000000
83,remainder__has_work_email,0.000000,0.000000
84,remainder__host_response_rate_missing,-0.000000,0.000000
85,remainder__host_acceptance_rate_missing,-0.000000,0.000000

Why log transforming target column was necessary

In [ ]:
# train test split
from sklearn.model_selection import train_test_split
X=df.drop(columns=['estimated_revenue_l365d','log_revenue'])
y = df['estimated_revenue_l365d']

X_train_2,X_test_2,y_train_2,y_test_2 = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
grid.fit(X_train_2,y_train_2)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['host_response_rate',
                                                                          'host_acceptance_rate',
                                                                          'host_listings_count',
                                                                          'host_total_listings_count',
                                                                          'latitude',
                                                                          'longitude',
                                                                          'accommodates',
                                                                          'bathrooms',
                                                                          'bedrooms',
                                                                          'beds',
                                                                          'price',
                                                                          'minimum_nights',
                                                                          'maximum_nights',
                                                                          'min...
       1.83298071e-02, 3.79269019e-02, 7.84759970e-02, 1.62377674e-01,
       3.35981829e-01, 6.95192796e-01, 1.43844989e+00, 2.97635144e+00,
       6.15848211e+00, 1.27427499e+01, 2.63665090e+01, 5.45559478e+01,
       1.12883789e+02, 2.33572147e+02, 4.83293024e+02, 1.00000000e+03])},
                         {'model': [ElasticNet(max_iter=10000)],
                          'model__alpha': [0.01, 0.1, 1, 10],
                          'model__l1_ratio': [0.1, 0.5, 0.9]}],
             scoring='neg_root_mean_squared_error')

In [ ]:
print("Best model:", grid.best_params_)
print("Best CV RMSE:", -grid.best_score_)

Best model: {'model': Lasso(max_iter=10000), 'model__alpha': np.float64(112.88378916846884)}
Best CV RMSE: 7758.882120242929

**Decision Tree Regressor & Random Forest Regressor**

In [27]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [28]:
dt_rf_pipeline = Pipeline([
    ('preprocessing', preprocessor),
    ('model', DecisionTreeRegressor(random_state=42))
])

In [35]:
dt_rf_param_grid = [
    {
        'model':[RandomForestRegressor(random_state=42)],
        'model__n_estimators': [5,10,25,50,75,100,150, 200],
        'model__max_depth': [None, 10, 20],
        'model__min_samples_split': [2, 5]
    },
    {
        'model':[DecisionTreeRegressor(random_state=42)],
        'model__max_depth': [None, 5, 10, 20],
        'model__min_samples_split': [2, 5, 10],
        'model__min_samples_leaf': [1, 2, 4]
}
    ]

In [36]:
grid=GridSearchCV(
    dt_rf_pipeline,
    dt_rf_param_grid,
    cv=5,
    scoring='neg_root_mean_squared_error',
    n_jobs=-1
)
grid.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['host_response_rate',
                                                                          'host_acceptance_rate',
                                                                          'host_listings_count',
                                                                          'host_total_listings_count',
                                                                          'latitude',
                                                                          'longitude',
                                                                          'accommodates',
                                                                          'bathrooms',
                                                                          'bedrooms',
                                                                          'beds',
                                                                          'price',
                                                                          'minimum_nights',
                                                                          'maximum_nights',
                                                                          'min...
             param_grid=[{'model': [RandomForestRegressor(random_state=42)],
                          'model__max_depth': [None, 10, 20],
                          'model__min_samples_split': [2, 5],
                          'model__n_estimators': [5, 10, 25, 50, 75, 100, 150,
                                                  200]},
                         {'model': [DecisionTreeRegressor(random_state=42)],
                          'model__max_depth': [None, 5, 10, 20],
                          'model__min_samples_leaf': [1, 2, 4],
                          'model__min_samples_split': [2, 5, 10]}],
             scoring='neg_root_mean_squared_error')

In [37]:
print("Best model:", grid.best_params_)
print("Best CV RMSE:", -grid.best_score_)

Best model: {'model': RandomForestRegressor(random_state=42), 'model__max_depth': None, 'model__min_samples_split': 2, 'model__n_estimators': 200}
Best CV RMSE: 0.12176453233146048

In [38]:
from sklearn.metrics import mean_squared_error
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)
rmse_test = np.sqrt(mean_squared_error(y_test, y_pred))
print("Test RMSE:", rmse_test)

Test RMSE: 0.09529078818503883